

module.exports.Admin = require('./admin.controller')
module.exports.UserController = require('./user.controller')
module.exports.ProductController = require('./product.controller')
module.exports.CategoryController = require('./categories.controller')
module.exports.UploadController = require('./upload.controller')
module.exports.CouponController = require("../controllers/coupon.controller")
module.exports.CartController = require('./cart.controller')
module.exports.WihslistController = require('./wishlist.controller')
module.exports.HomePageBannerController = require('./homepageBanner.controller')
module.exports.OrderController = require('./order.controller')
module.exports.BrandController = require('./brand.controller')
module.exports.AboutController = require('./about.controller')
module.exports.TermsAndConditionsController = require('./termsandconditons.controller')
module.exports.BlogController = require('./blogs.controller')
module.exports.NewsletterController = require('./newsletter.controller')
module.exports.ColorController = require('./color.controller')