
module.exports.Admin = require('./admin.service')
module.exports.UserService = require('./user.service')
module.exports.ProductService = require('./products.service')
module.exports.CatgeoryService = require('./categories.service')
module.exports.CouponService = require("./coupon.service")
module.exports.CartService = require("./cart.service")
module.exports.WishlistService = require("./wishlist.service")
module.exports.HomePageBannerService = require("./homepageBannerService")
module.exports.OrderService = require("./order.service")
module.exports.BrandService = require('./brand.service')
module.exports.AboutService = require('./about.service')
module.exports.TermsAndConditonsService = require('./termsandconditons.service')